[tool.black]
line-length = 100
target-version = ["py39"]
include = '\.pyi?$'
exclude = '\.git|__pycache__|build|dist|\.venv|\.env'
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
warn_unused_ignores = true
no_implicit_optional = true
show_error_codes = true
