name: Databricks CI/CD Pipeline

on:
  push:
    branches: [dev, test, uat, prod]
  pull_request:
    branches: [dev, test, uat, prod]

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  code-quality-checks:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch main branch
        run: git fetch origin main
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install flake8 black pytest databricks-cli pyyaml
          
      - name: Code formatting check
        run: black --check notebooks/
        
      - name: Lint code
        run: flake8 notebooks/ --max-line-length=88
        
      - name: Validate all cluster configs
        run: |
          for env in dev test uat prod; do
            file="configs/${env}_clusters.yaml"
            if [ ! -f "$file" ]; then
              echo "❌ Missing config file: $file"
              exit 1
            fi
            python -c "import yaml,sys; yaml.safe_load(open('$file'))" || exit 1
            echo "✅ $file is valid."
          done

  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch main branch
        run: git fetch origin main

      - name: Set up Python and dependencies
        run: |
          pip install databricks-cli pyyaml
          
      - name: Configure Databricks CLI
        run: |
          echo "$DATABRICKS_HOST" > ~/.databricks_host
          echo "$DATABRICKS_TOKEN" > ~/.databricks_token
          
      - name: Deploy cluster and notebooks
        run: |
          python deploy_script.py --env dev
          
  deploy-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test' && github.event_name == 'push'
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch main branch
        run: git fetch origin main

      - name: Set up Python and dependencies
        run: |
          pip install databricks-cli pyyaml
          
      - name: Deploy cluster and notebooks
        run: |
          python deploy_script.py --env test

  deploy-uat:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/uat' && github.event_name == 'push'
    environment: uat
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch main branch
        run: git fetch origin main

      - name: Set up Python and dependencies
        run: |
          pip install databricks-cli pyyaml
          
      - name: Deploy cluster and notebooks
        run: |
          python deploy_script.py --env uat

  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod' && github.event_name == 'push'
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch main branch
        run: git fetch origin main

      - name: Set up Python and dependencies
        run: |
          pip install databricks-cli pyyaml
          
      - name: Deploy cluster and notebooks
        run: |
          python deploy_script.py --env prod
