name: Databricks CI/CD Pipeline

on:
  push:
    branches: [dev, test, uat, prod]
  pull_request:
    branches: [dev, test, uat, prod]

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  detect-issues:
    runs-on: ubuntu-latest
    outputs:
      has_errors: ${{ steps.checks.outputs.has_errors }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # We'll re-auth for push later

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort pytest

      - name: Run all checks
        id: checks
        run: |
          echo "🚀 Detecting problems..."
          errors=0
          
          black --check . || errors=$((errors+1))
          flake8 . || errors=$((errors+1))
          isort --check-only . || errors=$((errors+1))
          pytest || errors=$((errors+1))

          if [ "$errors" -ne 0 ]; then
            echo "has_errors=true" >> $GITHUB_OUTPUT
          else
            echo "has_errors=false" >> $GITHUB_OUTPUT
          fi

  fix-issues:
    needs: detect-issues
    if: needs.detect-issues.outputs.has_errors == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with push permissions
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Auto-fix formatting
        run: |
          echo "🛠 Fixing formatting issues..."
          black .
          isort .

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-format code [skip ci]" || echo "No changes to commit"
          git push
